name: Laravel CI/CD config

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, pdo, pdo_mysql, openssl, tokenizer, xml, ctype, json
          coverage: none

      - name: Verify PHP version (CI)
        run: php -v

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist

      - name: Build frontend assets
        run: |
          npm ci
          npm run build

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          port: 2121
          script: |
            set -e

            cd /var/www/donasiweb
            echo "PHP version on VM"
            php -v

            echo "Reset broken vendor directory"
            sudo rm -rf vendor
            git checkout -- composer.lock

            echo "Install Composer dependencies"
            php /usr/local/bin/composer install \
              --no-dev \
              --optimize-autoloader \
              --no-interaction \
              --prefer-dist

            echo "Run migrations"
            php artisan migrate --force

            echo "Optimize Laravel"
            php artisan optimize
            php artisan config:clear
            php artisan view:clear

            echo "Reload PHP-FPM"
            sudo systemctl reload php8.2-fpm
